accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

blog_intern/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace='blogs')),
]

blogs/urls.py
from django.urls import path
from .views import blog_detail, postComment, shareBlog, writeBlog

app_name = 'blog'

urlpatterns = [
    path('<int:id>/', blog_detail, name='detail'),
    path('comment/', postComment, name='comment'),
    path('blog/share/', shareBlog, name='share'),
    path('write/', writeBlog, name='write'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class BlogModel(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'id': self.id})


class BlogComment(models.Model):
    comment = models.TextField()
    cauthor = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE)
    publish = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.comment

blogs/forms.py
from django.db import models
from django.db.models import fields
from django.forms import ModelForm
from .models import BlogComment, BlogModel


class BlogForm(ModelForm):
    class Meta:
        model = BlogModel
        fields = ('title', 'body')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

blogs/views.py
from .models import BlogModel, BlogComment
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .utils import send_mail_task
from django.conf import settings
from .forms import BlogForm
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def writeBlog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect('home')
        else:
            print('Blog Not Created')
    else:
        form = BlogForm()

    return render(request, 'blogs/create.html', context={'form': form})


def index(request):
    blogs = BlogModel.objects.all().select_related('author')
    
    context = {
        'blogs': blogs,

    }
    if request.user.is_authenticated:
        request_user_blogs = BlogModel.objects.filter(author=request.user)
        context['rblogs'] = request_user_blogs
    else:
        request_user_blogs = 'Please Login to see your blogs'
        context['no_blogs'] = True
    return render(request, 'home.html', context=context)


def blog_detail(request, id):
    blog_obj = BlogModel.objects.get(id=id)
    comments = BlogComment.objects.filter(
        blog=blog_obj).select_related('cauthor')
    
    context = {
        'blog': blog_obj,
        'comments': comments

    }
    
    if request.user.is_authenticated:
        request_user_blogs = BlogModel.objects.filter(author=request.user)
        context['rblogs'] = request_user_blogs
    else:
        request_user_blogs = 'Please Login to see your blogs'
        context['no_blogs'] = True

    return render(request, 'blogs/detail.html', context=context)


@csrf_exempt
def postComment(request):
    if request.method == 'POST':
        blog_id = request.POST.get('id')
        comment = request.POST.get('comment')
        blog_obj = BlogModel.objects.get(id=blog_id)
        if blog_obj:
            BlogComment.objects.create(
                comment=comment, cauthor=request.user, blog=blog_obj)

        subject = 'New Comment'
        blog_url = request.build_absolute_uri(blog_obj.get_absolute_url())

        message = f"{request.user.username} has posted a comment on your Blog {blog_url}"
        email_from = settings.EMAIL_HOST_USER
        recepient_list = [blog_obj.author.email]
        send_mail_task(subject=subject, message=message,
                       email_from=email_from, recepient_list=recepient_list)

        data = {
            'comment': comment,
            'author': request.user.username,
        }

        return JsonResponse(data)
    else:
        return JsonResponse({"error": "Error on posting comment"})


@csrf_exempt
def shareBlog(request):
    if request.method == 'POST':
        email = request.POST.get('user_email')
        id = request.POST.get('id')
        blog_obj = BlogModel.objects.get(id=id)

        subject = f'{request.user.username} shared a blog'
        url = request.build_absolute_uri(blog_obj.get_absolute_url())
        message = f'{request.user.username} has shared a blog with you, read it here {url}'
        email_from = settings.EMAIL_HOST_USER
        recepient_list = [email]
        send_mail_task(subject=subject, message=message,
                       email_from=email_from, recepient_list=recepient_list)
        return JsonResponse({'Success': 'Blog Shared Successfully'})
    else:
        return JsonResponse({'error': 'Could Not Share Blog'})

blogs/templates/blogs/create.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}

{% block title %}Create Blog{% endblock %}

{% block content %}
<div class="jumbotron">
    <h3>Create Blog</h3>
</div>
<div class="container mt-4">
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Publish">
    </form>
</div>
{% endblock %}

blogs/templates/blogs/detail.html
{% extends 'base.html' %}

{% block title %}{{blog.title}}{% endblock %}

{% block content %}

<style>
    .not-visible {
        display: none;
    }
</style>

<div class="container mt-3">
    <div class="row">
        <div class="col-xl-8 col-lg-7">
            <h4>{{blog.title|title}}</h4>
            <p>{{blog.body}}</p>
            <span>Written by <b>{{blog.author.username}}</b></span>
            <!-- Button trigger modal -->
            {% if request.user.is_authenticated %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Share this Blog
            </button>
            {% endif %}
            {% with comments.count as total_comments %}
            <h5>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h5>
            {% endwith %}
            <hr>
            {% if request.user.is_authenticated %}
            <form class="comment--form mt-4" id="comment_form" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <textarea class="form-control" id="comment-textArea" name="comment" placeholder="Comment Your View"
                        required></textarea>
                </div>
                <input type="hidden" name="id" id="blog_id" value="{{blog.id}}">
                <input type="submit" value="Post Comment" class="btn btn-primary">
            </form>
            {% else %}
            <h4>Please <a href="{% url 'accounts:login' %}">Login</a> to Comment on the blog</h4>
            {% endif %}
            <hr>
            <div class="comment_div" id="comment_div_id">
                <div class="spinner-grow text-success not-visible" role="status" id="loader">
                    <span class="sr-only">Loading...</span>
                </div>
                {% if comments %}
                {% for comment in comments %}
                <p>{{comment.comment}}</p>
                <span>Comment Posted By <b><i>{{comment.cauthor}}</i></b> on {{comment.publish}}</span>
                <hr>
                {% endfor %}
                {% else %}
                <h5>No Comments in this blog</h5>
                {% endif %}
            </div>
        </div>
        <div class="col-xl-4 test col-lg-5">
            <h5>My Blogs</h5>
            {% for rblog in rblogs %}
            <p><a href="{{rblog.get_absolute_url}}">{{rblog.title}}</a></p>
            {% endfor %}
            {% if no_blogs %}
            <h5>Please <a href="{% url 'accounts:login' %}">Login</a> to see your blogs</h5>
            {% endif %}
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="spinner-border text-primary not-visible" role="status" id="share-loader">
                <span class="sr-only">Loading...</span>
            </div>
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Share Blog</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" id="share-form">
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1"
                            placeholder="Email of user you want to share with" name="user_email" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Message(Optional)</label>
                        <textarea class="form-control" name="share_textArea" id="exampleFormControlTextarea1"
                            rows="3"></textarea>
                    </div>
                    <input type="submit" value="Share" class="btn btn-primary">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            <div class="alert alert-success not-visible" id="success-alert" role="alert">

            </div>
        </div>
    </div>
</div>

<script>
    const comment_div = document.getElementById('comment_div_id');
    const loader = document.getElementById('loader');
    $('#comment_form').submit(function (e) {
        e.preventDefault();
        var comment = document.getElementById('comment-textArea').value
        var id = document.getElementById('blog_id').value
        console.log(id);
        $.ajax({
            type: 'POST',
            url: '{% url "blogs:comment" %}',
            data: {
                'id': id,
                'comment': comment,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            beforeSend: function () {
                loader.classList.remove('not-visible');
            },
            success: function (response) {
                $('#comment_form').trigger('reset');
                loader.classList.add('not-visible');
                comment_div.innerHTML += `<p>${response.comment}</p>
                                            <span>Comment Posted By <b><i>${response.author}</i></b></span>
                                          <hr>`;
            },
            error: function (error) {
                console.log(error);
            }
        });
    });

    const share_loader = document.getElementById('share-loader')

    $('#share-form').submit(function (e) {
        e.preventDefault();
        const user_email = document.getElementById('exampleFormControlInput1').value;
        var id = document.getElementById('blog_id').value;
        const success_alert = document.getElementById('success-alert');

        $.ajax({
            type: 'POST',
            url: '{% url "blogs:share" %}',
            data: {
                'user_email': user_email,
                'id': id,

            },
            dataType: 'json',
            beforeSend: function () {
                share_loader.classList.remove('not-visible');
            },
            success: function (response) {
                $('#share-form').trigger('reset');
                share_loader.classList.add('not-visible');
                success_alert.classList.remove('not-visible');
                success_alert.innerHTML = `${response.Success}`
            },
            error: function (error) {
                console.log(error);
            }
        });
    });
</script>
{% endblock %}