accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

blog_intern/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace='blogs')),
]

blogs/urls.py
from django.urls import path
from .views import blog_detail, postComment, shareBlog, writeBlog

app_name = 'blog'

urlpatterns = [
    path('<int:id>/', blog_detail, name='detail'),
    path('comment/', postComment, name='comment'),
    path('blog/share/', shareBlog, name='share'),
    path('write/', writeBlog, name='write'),
]

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Blogs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:write' %}">Write Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
        {% else %}
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>
    {% block content %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home/Blogs{% endblock %}

{% block content %}

<style>

</style>

<div class="container mt-3">
    <div class="row">
        <div class="col-xl-8 col-lg-7">
            <h3>Browse Blogs</h3>
            <hr>
            {% if blogs %}
            {% for blog in blogs %}
            <h5><a href="{{blog.get_absolute_url}}">{{blog.title|title}}</a></h5>
            <span>Written By: <b>{{blog.author.username}}</b> on {{blog.publish}}</span>
            <p>{{blog.body|truncatechars:30}}</p>
            <hr>
            {% endfor %}
            {% else %}
            <h4>Nothing here to show</h4>
            {% endif %}
        </div>
        <div class="col-xl-4 test col-lg-5">
            <h5>My Blogs</h5>
            {% for rblog in rblogs %}
            <p><a href="{{rblog.get_absolute_url}}">{{rblog.title}}</a></p>
            <hr>
            {% endfor %}
            {% if no_blogs %}
            <h5>Please <a href="{% url 'accounts:login' %}">Login</a> to see your blogs</h5>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}